name: SonarCloud
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@db501078e936e4b4c8773d1bb949ba9ddb7b6b6a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }}
        with:
          args:
            -Dsonar.projectKey=my-mqtt-stater-parent
            -Dsonar.organization=lionel13-github
